### ISSUE TITLE
Research what configAllowableClosedLoopError is

### ISSUE THREAD

**Issue by Yand1** [The-Charge/PlyBot2018#34]

**Comment by JessicaKline** [comment]
Seems to be small base value of error that's acceptable. Like a deadband for the PID Loop kind of.
From CTRE descrption of new Talon features
"User can now select the nominal forward and reverse output during Closed-Loop.  This means that if the Closed Loop Error is nonzero (or outside of the Allowable Closed-Loop Error) but the Closed-Loop calculates a motor output that is weaker than the specified nominal value, Talon will promote the motor output to the nominal value."

"User can now select the Allowable Closed-Loop error so that the motor drive remains neutral even if closed-loop error is nonzero."
